      - name: Install dependencies
        yum:
          name: "{{ item }}"
          state: present
        with_items:
          - epel-release
          - python
          - python-pip
          - python3
          - python3-pip
        
        
        # apt: 
        #   name: "{{ item }}" 
        #   state: present
        # with_items:
        #   - python
        #   - python-setuptools
        #   - python-dev
        #   - build-essential
        #   - python-pip
        #   - python-mysqldb