---
# tasks file for mysql_db

      - name: Install wget
        yum:
          name: wget
          state: present

      - name: Get MySQL repo
        shell: wget http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm

      - name: Install MySQL repo
        yum:
          name: mysql-community-release-el7-5.noarch.rpm
          state: present
        become: yes
        # shell: sudo rpm -ivh mysql-community-release-el7-5.noarch.rpm

      - name: Get latest update
        yum:
          name: '*'
          state: latest

      - name: Install MySQL database
        yum:
          name: "{{ item }}"
          state: present
        with_items:
          - mysql-server
          - MySQL-python
        ignore_errors: yes

      - name: Start Mysql Service
        service:
          name: mysql
          state: started
          enabled: yes

      # - name: Create Application Database
      #   mysql_db: 
      #     name: "{{ db_name }}"
      #     state: present
      #   ignore_errors: yes


      # - name: Create Application DB User
      #   mysql_user: 
      #     name: "{{ db_user }}" 
      #     password: "{{ db_user_password }}" 
      #     priv: '*.*:ALL' 
      #     host: '%' 
      #     state: 'present'
      #   ignore_errors: yes